### ISSUE TITLE
Transposes for GDMats and GLMats

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMat#19]
Version: d2b1d59c7566c15d5acb095549311434e294bef4

Seems like there's a link error.

>scala> val a8 = BIDMat.GDMat(BIDMat.DMat(1 on 4))
>a8: BIDMat.GDMat =
>  1
>  4
>
>scala> a8.t
>java.lang.UnsatisfiedLinkError: edu.berkeley.bid.CUMATD.transpose(Ljcuda/Pointer;ILjcuda/Pointer;III)I
>  at edu.berkeley.bid.CUMATD.transpose(Native Method)
>  at BIDMat.GDMat.t(GDMat.scala:301)
>  ... 33 elided

The only difference is that the GDMats and GLMats use this:
CUMATD.transpose(this.data, nrows, out.data, ncols, nrows, ncols)

whereas GIMats and GMats use
CUMAT.transpose(this.data, nrows, out.data, ncols, nrows, ncols)

**Comment by jcanny** [comment]
Hmm,
GLMat and GDMat transpose are working for me. Can you tell me about your 
configuration?

If you're pull code from the master branch, you periodically need to 
rebuild the native code as well as the scala code. Or you can grab the 
latest binaries from stout in /code/BIDMat/lib

-John

**Comment by DanielTakeshi** [comment]
Unfortunately, I seem to be getting these issues despite pulling again from master today and re-compiling BIDMat (./sbt package and then copying over the .jar). I think it may be a Mac-related issue (using OS X 10.9.5, Mavericks now) since running "make" fails in the BIDMat/jni/src directory. Let me test this out with other systems...

**Comment by jcanny** [comment]
You need to rebuild the native lib, since the older ones dont have 
double/long support. It should work in a Maverics Mac (Does for me). You 
need to have Mac compiler (Xcode) tools and CUDA installed on your Mac. 
Both are free.

-john

**Comment by DanielTakeshi** [comment]
Works after downloading the 1.0 release.

**Comment by jcanny** [comment]
Hi Daniel,
Could you send me the reference for the current ICA implementation, and 
some sample datasets I can try out?

-John

**Comment by DanielTakeshi** [comment]
John,

Here are the three papers I'm using:

(1) "Independent Component Analysis, Algorithms and Applications"
(2) "The Fixed-Point Algorithm and Maximum Likelihood Estimation for ICA"
(3) "Fast and Robust Fixed-Point Algorithms for ICA"

More specific information:

(1) Equation 25 in this paper has the approximation of negentropy that I'm
using, and I think this goes in the evalfun. Section 6 explains the FastICA
algorithm. The current ICA implementation uses Equation 47 (from Section
6.3) which is the fixed point update I was mentioning. The matrix needs to
be orthogonalized after every step, and I am using the fixed point
iterative update as described in equation 46, using the largest absolute
row norm (as they suggested).
(2) This paper sort of explains how to get that maximum likelihood
estimation fixed point algorithm, though it's not in depth, but could be
useful to fill in a few blanks from the first paper. (This paper is
probably the least useful of the three I've listed.)
(3) This goes in more detail on the contrast functions and how the fixed
point algorithm works. In particular, section 4.3 shows that to avoid
whitening the data, we can actually put the covariance matrix in the
orthogonalization step (equation 26), as I do in ICA.scala. Based on my
test results that I've shown you, the fixed point algorithm that I saw in
the first paper (equation 47 as mentioned earlier) apparently can work with
non-whitened data so long as the orthogonalization step includes the
covariance matrix. I don't have a deep understanding of how this math
works, though -- I tried but the algebra got insane.

I'm currently getting a script set up for testing it (I had an earlier one
but am making a better one), but in the meantime, you can probably read
about the algorithms and see how they work. I'm also going to fix the ICA
code after I get the test set up. Expect an update later this afternoon or
tonight.

Daniel
