### ISSUE TITLE
Exposing code that returns "empty" DenseMats?

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMat#20]
Version: 38035fd80f1e0a16c85ae88fa266808a919ba4c6

I was looking through the DenseMat.scala code to document it. (I was going to document this one, then copy and paste some of the comments elsewhere.) I noticed that there are many methods that return an appropriate matrix internally, but will not print it out on the command line. Do you think this may confuse other/new users? Is it worthwhile to just set those methods to be private or package-protected?

Here are two examples:

(1) DenseMat has mkdiag and getdiag methods that sort of act as a "second" way of getting diagonals. For instance, the usual way to make a diagonal matrix is as the following:

scala> val a = mkdiag(1 on 2 on 3)
a: BIDMat.IMat =
   1   0   0
   0   2   0
   0   0   3

Though I can also do it this way:

scala> val a = (1 on 2 on 3).mkdiag
a: BIDMat.DenseMat[Int] =

scala> 

While it's subtle, the second way actually produces a correct matrix, but it just doesn't print out normally and we have to wrap an IMat() around it to "see" it normally. The same holds true for getdiag. 

Second example:

scala> val b = DMat(1\2 on 3\4)
b: BIDMat.DMat =
   1   2
   3   4

scala> b.ghorzcat(b)
res10: BIDMat.DenseMat[Double] =

scala> DMat(b.ghorzcat(b))
res11: BIDMat.DMat =
   1   2   1   2
   3   4   3   4

**Comment by jcanny** [comment]
Hmm,
DenseMat is not supposed to be exposed directly. It should probably be 
virtual, except that I need concrete instances of Densemat to be wrapped 
by the actual matrix classes. There should be an IMat mkdiag method that 
wraps the densemat version. And to make sure, the densemat version 
should be renamed to _mkdiag.

-john

**Comment by DanielTakeshi** [comment]
Right, the IMat, DMat, etc. all have mkdiags that can wrap around things.

Should we change all DenseMat methods to have an extra underscore? I noticed that happened with a lot of the "_update" methods.

Btw there's some more documentation for LDA, MatFunctions, and DenseMat, and more is coming for ICA. Feel free to add then to the API (and please let me know what commands you used since sbt doc doesn't seem to work, there's a step I'm missing).

**Comment by jcanny** [comment]
Yes, its better for the internal methods to use an underscore. It would also be better to make them protected, assuming this doesnt break anything.
