### ISSUE TITLE
Error in wiki

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMat#21]
In the wiki/Dictionaries page, there is a reference to a `union2` method of the `Dict` class:

``` >val (d, dm1, dm2) = Dict.union2(d1,d2) ```

I think this should actually be `Dict.union3(d1,d2)`? The `union2` command seems to apply to IDicts.

**Comment by DanielTakeshi** [comment]
Thanks for noticing this typo. I found a few other typos on the Wiki page, which I have fixed.
