### ISSUE TITLE
Google groups for BidMat and BidMach

### ISSUE THREAD

**Issue by kishorenayar** [BIDData/BIDMat#23]
Hi, Do you guys have google groups for BidMach and BidMat projects ?

**Comment by DanielTakeshi** [comment]
I am 99.9% sure we do not have a group. If there become more BIDMach/BIDMat users, we might create one in the future.

**Comment by jcanny** [comment]
Hi Daniel,
Yes, I did create one for future use. I'm not really using it, but it 
would be good to try to get it started...

-john

**Comment by kishorenayar** [comment]
Hi All, 

  Thanks for the update.
