### ISSUE TITLE
install trouble ubuntu

### ISSUE THREAD

**Issue by knavely** [BIDData/BIDMat#38]
./bidmat
Error: Could not find or load main class scala.tools.nsc.MainGenericRunner

I have tried with scala 2.11.2 and 2.10.4
i have java version 1.7.0_80

**Comment by jcanny** [comment]
We need a lot more context to figure out what the problem is, i.e. where you got BIDMat from, if you built it etc. BIDMat is working fine for most people. The bundles  downloadable from here
http://bid2.berkeley.edu/bid-data-project/download/
include a copy of scala so you dont need one installed. The error message suggests it couldnt load scala so perhaps another version shadowing the included version (do you set a global CLASSPATH?)

**Comment by knavely** [comment]
I was following the setup guide and install.txt. Which I think amounted to installing Cuda and cloning the bidmat repo and ran the bidmat script. Perhaps I missed a step with the bundles? 

Thanks!

**Comment by DanielTakeshi** [comment]
The installation requires a lot of libraries that are not in the repository. What is in your `BIDMat/lib` directory? For reference, here's what I have (hoping this copy/paste thing shows up well on Markdown):

```
Apache_Commons_Math_LICENSE.txt		jcublas-0.7.0a.jar			jhdf5.dll				libJCusparse2-apple-x86_64.dylib	libjhdf5.jnilib
Apache_License.txt			jcuda-0.7.0.jar				jhdf5.jar				libbidmatcuda-apple-x86_64.dylib	libjhdf5.so
BIDMat.jar				jcuda-0.7.0a.jar			jline-2.11.jar				libbidmatmkl-apple-x86_64.dylib		lz4-1.3.0.jar
HDF5_Copyright.html			jcufft-0.7.0.jar			junit-4.11.jar				libiomp5.dylib				lz4-1.3.jar
IScala.jar				jcufft-0.7.0a.jar			libJCublas-apple-x86_64.dylib		libiomp5.so				osx32
IScala_license.txt			jcurand-0.7.0.jar			libJCublas2-apple-x86_64.dylib		libiomp5.soxxx				osx64
JCUDA_Copyright.txt			jcurand-0.7.0a.jar			libJCudaDriver-apple-x86_64.dylib	libjhdf-apple-x86.jnilib		ptplot.jar
PtPlot_Copyright.txt			jcusolver-0.7.0.jar			libJCudaRuntime-apple-x86_64.dylib	libjhdf.jnilib				ptplotapplication.jar
Scala_License.txt			jcusolver-0.7.0a.jar			libJCufft-apple-x86_64.dylib		libjhdf.so				sbt-launch.jar
bidmat_init.scala			jcusparse-0.7.0.jar			libJCurand-apple-x86_64.dylib		libjhdf5-apple-x86.jnilib		scala-parser-combinators_2.11-1.0.2.jar
commons-math3-3.2.jar			jcusparse-0.7.0a.jar			libJCusolver-apple-x86_64.dylib		libjhdf5-apple-x86_64.jnilib		scalacheck_2.11-1.11.6.jar
jcublas-0.7.0.jar			jhdf.dll				libJCusparse-apple-x86_64.dylib		libjhdf5.dylib				scalatest_2.11-2.2.1.jar
```

**Comment by jcanny** [comment]
Try googling "Installing BIDMat" which should take you to the page: 
https://github.com/BIDData/BIDMat/wiki/Installation
which tells you to download code bundles with the binary libs already compiled for your platform. It also contains all the jars you need. You can still use github to get the latest source, but you should copy the binaries as per that docs page.

**Comment by knavely** [comment]
Thanks, yes I had done this , I think I missed something about getting the
dependencies in the installation page. Apologies
