### ISSUE TITLE
TParse behaviors with string type different from the document

### ISSUE THREAD

**Issue by qiaojianjack** [BIDData/BIDMat#46]
Now the TParse code output an IMat and a SBMat for a column of strings with delimeters in the raw data file. Each row of the IMat is a `(row, keyword_id)` pair, where the row number corresponds to the row number in the input data file, and keyword_id is the id of a keyword in the SBMat dictionary of unique keywords.

However, in the document for TParse behavior on string data (https://github.com/BIDData/BIDMach/wiki/Data-Wrangling#String_Fields), it says TParse will output an SMat and a SBMat for a column of strings with delimeters in the raw data file, where each column of the SMat is a list of keyword_ids. 

It seems that there should be an extra step from the current TParse result to the intended behavior in the document, in which the IMat is converted to the SMat according to the specification of the encoding. Can anyone either fix the document or fix the code?

**Comment by jcanny** [comment]
I'll update the document. Outputing SMat's turns out to be a bad idea for datasets with large vocabularies. An SMat can only hold 24 bits of word id (limiting the vocab to about 16 million words). The IMat version can handle vocabs of 2^31 words, which covers a much larger set of cases.

**Comment by acrossen** [comment]
The way I get to the SMat is to take TParse's IMat and "collapse" it to an RCV file containing `(doc_id, term_id, term_freq)` triples.  From there you can run cols2sparse on the RCV file to get the SMat.

```
  def createRCVTripleFile(a:IMat, rcv_triple_file:String) = {
    var curDocID = 0
    var rows_written = 0
    val termIDToFreq = new HashMap[Int,Int]()
    val gout = HMat.getOutputStream(rcv_triple_file, 0)
    val fout = new BufferedWriter(new OutputStreamWriter(gout))
    for(i <- 0 until a.nrows) {
      val thisDocID = a(i,0)
      // change of doc id, or end of matrix
      if(thisDocID != curDocID || (i == a.nrows-1)) {
        for((termID,freq) <- termIDToFreq) {
          fout.write(curDocID + " " + termID + " " + freq + "\n")
          rows_written += 1
        }
        termIDToFreq.clear()
        curDocID = thisDocID
      }
      if(i < a.nrows-1) {
        val thisTermID = a(i,1)
        val curFreq = termIDToFreq.getOrElse(thisTermID, 0)
        termIDToFreq.put(thisTermID, curFreq+1)
      }
    }
    fout.close
    (rows_written)
  }

val rows_written = createRCVTripleFile(a, rcv_triple_file)
val rcv = loadDMat(rcv_triple_file)
val stdm = cols2sparse(rcv, true, false, 0)
stdm.check
saveSMat(smat_file, stdm)
```

**Comment by jcanny** [comment]
The tparse documentation has been updated. Also, both tparse and the xml parsers have been updated to output zero-based indices for word ids. The one-based indices were causing a lot of confusion.
