### ISSUE TITLE
specify number of GPUs to use?

### ISSUE THREAD

**Issue by mjparrott** [BIDData/BIDMat#57]
Looking through the code, I couldn't find a way to specify the number of GPUs to use on the machine. Is this possible?

**Comment by jcanny** [comment]
We dont have such a hook, but you can specify the set of GPUs visible to a shell process before you start BIDMat/ch by setting 
export CUDA_VISIBLE_DEVICES=0,1,..
bidmat

this works in Linux and MacOS. If you're using Cygwin, you cant set windows variables from the shell. But you can set them from the windows shell containing your cygwin terminal, i.e. in the "Target" field of the properties of the cygwin terminal shortcut. Or you could make a shortcut to a windows script that the calls cygwin mintty...
