### ISSUE TITLE
BIDMat binaries for cuda 7.5 on Ubuntu ?

### ISSUE THREAD

**Issue by rcherukuri12** [BIDData/BIDMat#60]
Hello,
Any plans to update BIDmat / mach binaries with current cuda toolkit ?

**Comment by jcanny** [comment]
yes, CUDA 7.5 is supported now. clone from github, and ./getdevlibs.sh will download the appropriate libs for your CUDA version (assuming its 7.0 or 7.5 :)

We also added maven building. See the Installation instructions.
