### ISSUE TITLE
How to run the test scripts?

### ISSUE THREAD

**Issue by javadba** [BIDData/BIDMat#67]
Here is a portion of one of them: scripts/testcomm.ssc

```
import BIDMat.AllReduce;

val gmods = irow(4,2);
val M = prod(gmods).v;

```
Well  neither *irow* nor *prod* have been properly imported .. so this script is going to fail..  Any comments on this?

**Comment by DanielTakeshi** [comment]
Do you run them on the command line?

`./bidmach scripts/testcomm.scc`

The `./bidmach` command loads in a bunch of stuff.

**Comment by javadba** [comment]
Running with *bidmach* appears to take care of it.

**Comment by jcanny** [comment]
Both bidmach and sbt console should load the init scripts in BIDMach/lib/bidmach_init.scala

How did you run bidmach?

**Comment by javadba** [comment]
I had run it simply via the scala command (and with lib/* in the classpath).  You guys put some magic sauce in the sbt console afa imports  - so I was missing those.

**Comment by javadba** [comment]
Some of the scripts do not work - even now. Try running bidmach scripts/runICA.ssc

Instead: running python scripts/runICA.py works well.

**Comment by DanielTakeshi** [comment]
Sorry that runICA.ssc is outdated. I removed it (a few weeks ago).
