### ISSUE TITLE
Error happens when trying to load ".mat" data from MATLAB

### ISSUE THREAD

**Issue by xinleipan** [BIDData/BIDMat#68]
I'm trying to load some ".mat" data from MATLAB and my code is:

val a:Mat = load("data.mat","TrainImg")

where the "data.mat" locate in the root folder of bidmach. However, I got the following errors:

HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  #000: /Users/byrn/Documents/hdfprojects/JNI-3.2/buildstatic/native/HDF5-prefix/src/HDF5/src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
hdf.hdf5lib.exceptions.HDF5FileInterfaceException: Unable to open file
  at hdf.hdf5lib.H5._H5Fopen(Native Method)
  at hdf.hdf5lib.H5.H5Fopen(H5.java:2762)
  at BIDMat.MatHDF5$.hload(MatHDF5.scala:531)
  at BIDMat.MatFunctions$.load(MatFunctions.scala:1988)
  ... 33 elided

I just save the file using normal "save as..." in matlab. Any help? Really appreciated.

**Comment by jcanny** [comment]
Before posting an error report you should make some efforts to figure out if its an elementary bug. The error message says it couldnt open the file, so either the file isnt there or it doesnt have read permissions. Like most tools, BIDMat's paths are relative to where the tool is started from, not its root directory. To determine this, you could try a saveAs from BIDMat first (which would also tell you if the HDF5 libs are working correctly) and look where the file is saved to. 

The error message (inherited from the HDF5 libraries so unfortunately we cant change them) suggest that there is a file permission problem. Are you sure you have read permission for that file and its parent directories?

**Comment by xinleipan** [comment]
Thanks, this problem has been fixed. It is that I shouldn't just right click on the data in MATLAB and save as ".mat" files. Since the default MAT-version is not '-v7.3', which is required by the "load" function in BIDMat. Instead, I should run "save('data.mat','-mat','-v7.3')" in MATLAB and this works right now.

**Comment by jcanny** [comment]
This is described in the docs:
https://github.com/BIDData/BIDMat/wiki/Loading-and-saving-matrices
