### ISSUE TITLE
broadcasting operations in BIDMat?

### ISSUE THREAD

**Issue by xinleipan** [BIDData/BIDMat#72]
Any function in BIDMat that can do something similar to broadcasting in python? For example we have a matrix X of size 1 * N, and a matrix t of size 1 * n, we want to get a matrix of size n * N, where every row of the resultant matrix is (X - t(i)).

**Comment by DanielTakeshi** [comment]
There's a lot of broadcasting in BIDMach. Example:

```
scala> val a = rand(3,3)
a: BIDMat.FMat =
   0.62465   0.26990   0.39953
   0.63891  0.050579   0.91040
   0.84862   0.73763   0.49750

scala> val b = ones(3,1)
b: BIDMat.FMat =
   1
   1
   1

scala> a + b
res3: BIDMat.FMat =
  1.6247  1.2699  1.3995
  1.6389  1.0506  1.9104
  1.8486  1.7376  1.4975
```

**Comment by xinleipan** [comment]
Thanks, in the particular case I mentioned above where X is just 1 * N but the result should be n * N dimension, simply X - t does not work. One solution I can think of it's to replicate X in multiple rows and deduced by t.t (t transpose). Any alternatives?

**Comment by xinleipan** [comment]
I see. We can use the function kron for this purpose.

**Comment by DanielTakeshi** [comment]
Yeah, glad that worked! The kron operator is definitely useful.

I'm closing this question, since it seems like it was resolved.
